Documentation: remove "git pull --porcelain"
This option was added to git-fetch in dd781e3856 and is
documented as valid for git-pull via inclusion but is not actually
accepted as a valid argument:

    $ git pull --porcelain
    error: unknown option `porcelain'
    usage: git pull [<options>] [<repository> [<refspec>...]]

Similar to other fetch options that are not valid for pull, remove it
from the man page using an ifndef directive.

Signed-off-by: Carl Brasic <cbrasic@gmail.com>